version: '3.5'

services:
  db:
    image: postgres:10.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 3306:3306
  postgres-gui:
    image: donnex/pgweb
    command: -s --bind=0.0.0.0 --listen=8080 --url postgresql://postgres:@postgres/api_dev?sslmode=disable
    links:
      - db:postgres
    ports:
      - "8080:8080"
  api:
    build: ./api
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/app
      - ./api/vendor/bundle:/app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
  front:
    build: ./front
    command: yarn start
    volumes:
      - ./front:/app
    ports:
      - 8000:3000
volumes:
  postgres-data:
    driver: local
