swagger: '2.0'
info:
  description: This is API for full stack first step
  version: 1.0.0
  title: FullStackFirstStepAPI
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: g2119001@fun.ac.jp
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:3000'
basePath: /api/v1
tags:
  - name: ParentTasks
    description: Operations about ParentTasks
  - name: User
    description: Operations about user
schemes:
  - http
paths:
  /parent_tasks:
    get:
      tags:
        - ParentTasks
      summary: get all parent_tasks that user have
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: "Bearer {access_token}"
          type: string
      responses:
        '200':
          description: Valid input
          schema:
            $ref: '#/definitions/ParentTaskGetResponse'
        '401':
          description: Unauthorized
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "error"
              message:
                type: "string"
                example: "token_must_be_passed"
    post:
      tags:
        - ParentTasks
      summary: create new parent_task
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: "Bearer {access_token}"
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        '200':
          description: Creating parent_task is success
          schema:
            $ref: '#/definitions/ParentTaskPostResponse'
        '401':
          description: Unauthorized
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "error"
              message:
                type: "string"
                example: "token_must_be_passed"

  '/parent_tasks/{id}':
    put:
      tags:
        - ParentTasks
      summary: update parent_task by specifying from id
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: "Bearer {access_token}"
          type: string 
        - in: path
          name: id
          description: "id of parent_task"
          type: integer
          required: true
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        '200':
          description: Updating parent_task is success
          schema:
            $ref: '#/definitions/ParentTaskPutResponse'
        '401':
          description: Unauthorized
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "error"
              message:
                type: "string"
                example: "token_must_be_passed"
        '403':
          description: You do not have permission
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "ERROR"
              message:
                type: "string"
                example: "You do not have permission"
    delete:
      tags:
        - ParentTasks
      summary: delete parent_task by specifying from id
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: "Bearer {access_token}"
          type: string
        - in: path
          name: id
          description: "id of parent_task"
          type: integer
          required: true
      responses:
        '200':
          description: Deleting parent_task is success
          schema:
            $ref: '#/definitions/ParentTaskDeleteResponse'
        '401':
          description: Unauthorized
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "error"
              message:
                type: "string"
                example: "token_must_be_passed"
        '403':
          description: You do not have permission
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                example: "ERROR"
              message:
                type: "string"
                example: "You do not have permission"
  /register/:
    post:
      tags:
        - User
      summary: Registrate User
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Registration_User'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/RegisterResponse'
        '400':
          description: "Bad Request"
  /login/:
    post:
      tags:
        - User
      summary: Sign in
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: login success
          schema:
            $ref: '#/definitions/LoginResponse'
  /oauth/twitter:
    get:
      tags:
        - User
      summary: twitter authentification
      description: "If you access \"api/v1/oauth/twitter\", will be open twitter authentification screen. If you authorize by twitter, redirect to \"localhost:8000\". Then access_token and refresh_token are in the URL. So you can get them from the URL"
      produces:
        - application/json
      responses:
        default:
          description: successful operation
      
definitions:
  Registration_User:
    type: object
    properties:
      user:
        type: object
        properties:
          email:
            type: string
          password:
            type: string
          password_confirmation:
            type: string
  User:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  Task:
    type: object
    required:
      - content
      - progress
    properties:
      content:
        type: string
      progress:
        type: integer
        format: int64
  RegisterResponse:
    type: object
    properties:
      status:
        type: "string"
        example: "success"
      data:
        type: "object"
        properties:
          access_token:
            type: "string"
            example: "yJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOCIsImV4cCI6IjE1NzAxNjI4NDgifQ.346wbegLKS2xPO6rLGc9KNTflyFc5MBkuhT4dNFfaRE"
          refresh_token:
            type: "string"
            example: "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOCIsImV4cCI6IjE1NzI3OTA3OTQifQ.Jo1fakLRNQUTmRhvD8Ecf3H1PsKad4teTCl7pMrcZS8"
          user:
            type: "object"
            properties:
              id:
                type: "integer"
                example: 8
              email:
                type: "string"
                example: "hoge@example.com"
              crypted_password:
                type: "string"
                example: "$2a$10$4swk4Jb7FqdjY9SNQcXcNOy1ue2HzZhrEJdYTBboWziKx0fWR5RCq"
              salt:
                type: "string"
                example: "aPrzmodcU2zQhkbzt3GJ"
              refresh_token:
                type: "string"
                example: "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOCIsImV4cCI6IjE1NzI3OTA3OTQifQ.Jo1fakLRNQUTmRhvD8Ecf3H1PsKad4teTCl7pMrcZS8"
              created_at:
                type: "string"
                example: "2019-10-04T03:50:48.554Z"
              updated_at:
                type: "string"
                example: "2019-10-04T03:50:48.570Z"
              password:
                example: null
              password_confirmation:
                example: null
  LoginResponse:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
      data:
        type: "object"
        properties:
          access_token:
            type: "string"
            example: "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOSIsImV4cCI6IjE1NzAxNjM1NzMifQ._r-Xdc318OCq7G3-tnJQTPCoPxgybDgcghWykIczVqQ"
          refresh_token:
            type: "string"
            example: "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiOSIsImV4cCI6IjE1NzI3OTE1MTkifQ.JCeF3p2mfcrF6MrenBrCrC2px4drljUpFrJVi2E5i98"
  ParentTaskGetResponse:
    type: "object"
    properties:
      status:
        type: "string"
        example: "SUCCESS"
      message:
        type: "string"
        example: "Loaded parent_tasks"
      data:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
            example: 1
          content:
            type: "string"
            example: "これはタスクだよ"
          user_id:
            type: "integer"
            format: "int64"
            example: 1
          progress:
            type: "integer"
            format: "int64"
            example: 52
          created_at:
            type: "string"
            example: "2019-10-03T06:53:57.536Z"
          updated_at:
            type: "string"
            example: "2019-10-03T06:53:57.536Z"
  ParentTaskPostResponse:
    type: "object"
    properties:
      status:
        type: "string"
        example: "SUCCESS"
      data:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
            example: 1
          content:
            type: "string"
            example: "これはタスクだよ"
          user_id:
            type: "integer"
            format: "int64"
            example: 1
          progress:
            type: "integer"
            format: "int64"
            example: 52
          created_at:
            type: "string"
            example: "2019-10-03T06:53:57.536Z"
          updated_at:
            type: "string"
            example: "2019-10-03T06:53:57.536Z"
  ParentTaskPutResponse:
    type: "object"
    properties:
      status:
        type: "string"
        example: "SUCCESS"
      message:
        type: "string"
        example: "Updated the task"
      data:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
            example: 1
          content:
            type: "string"
            example: "これはタスクだよ"
          user_id:
            type: "integer"
            format: "int64"
            example: 1
          progress:
            type: "integer"
            format: "int64"
            example: 52
          created_at:
            type: "string"
            example: "2019-10-03T06:53:57.536Z"
          updated_at:
            type: "string"
            example: "2019-10-03T06:53:57.536Z"
  ParentTaskDeleteResponse:
    type: "object"
    properties:
      status:
        type: "string"
        example: "SUCCESS"
      message:
        type: "string"
        example: "Deleted the task"
      data:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
            example: 1
          content:
            type: "string"
            example: "これはタスクだよ"
          user_id:
            type: "integer"
            format: "int64"
            example: 1
          progress:
            type: "integer"
            format: "int64"
            example: 52
          created_at:
            type: "string"
            example: "2019-10-03T06:53:57.536Z"
          updated_at:
            type: "string"
            example: "2019-10-03T06:53:57.536Z"
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
